version: '3.4'

services:
  app:
    container_name: gses2-btc-app
    image: gses2-btc-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
